_module_src: models.category_embedding
_model_name: CategoryEmbeddingModel
_backbone_name: CategoryEmbeddingBackbone
_config_name: CategoryEmbeddingModelConfig

task: regression
head: LinearHead
head_config:
    layers: ""
    activation: ReLU
    dropout: 0.1
    use_batch_norm: False
    initialization: kaiming
learning_rate: 1e-3
loss: L1Loss
metrics:
  - mean_absolute_error
  - pearson_corrcoef
target_range: null
seed: 42

layers: "64-32-16"
activation: LeakyReLU
use_batch_norm: False
initialization: kaiming
dropout: 0.1
