target:
- Age
continuous_cols:
- CXCL9
- CCL22
- IL6
- PDGFB
- CD40LG
- IL27
- VEGFA
- CSF1
- PDGFA
- CXCL10
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: quantile_normal
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true