_module_src: models.gandalf
_model_name: GANDALFModel
_backbone_name: GANDALFBackbone
_config_name: GANDALFConfig

task: regression
head: LinearHead
head_config:
  layers: ""
  activation: ReLU
  dropout: 0.1
  use_batch_norm: false
  initialization: xavier
learning_rate: 1e-3
loss: L1Loss
metrics:
  - mean_absolute_error
  - pearson_corrcoef
target_range: null
seed: 1337

gflu_stages: 6
gflu_dropout: 0.0
gflu_feature_init_sparsity: 0.3
